### PR TITLE
[Resolving Issue #72] Implemented slash-search

### PR DESCRIPTION
**Pull request by harjyotbagga**
Implemented Slash-Search. A command to use the slack bot to get StackOverflow links for the doubts a user has.
Can be invoked by **/search <query>**
Resolves Issue #72

### CODE REVIEW

**Comment by aaron-suarez** [comment]
I'm not sure what the problem is, but I can't seem to install the new dependency
```
$ poetry install
Installing dependencies from lock file
                                  
[NonExistentKey]   
'Key "hashes" does not exist.'  
                                  
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

**Comment by harjyotbagga** [comment]
I used bs4 to run my code, and thus had to install it. That's when I rebuilt the lock file.
What I see is the issue https://github.com/python-poetry/poetry/issues/1510.
Which suggests to delete the lock file and regenerate it.

**Comment by harjyotbagga** [comment]
Just to confirm, I added the dependency with `poetry install bs4` which made changes in the lock file.

**Comment by aaron-suarez** [comment]
Screen Shot 2020-10-08 at 5 26 10 PM

I don't know if we're going to be able to use `/search`. I think that's why the original issue had `!search`

**Comment by harjyotbagga** [comment]
Have made the changes, will make a new PR to merge.

**Comment by aaron-suarez** [comment]
#233

**Pull request closed without merging**
