### PR TITLE
Send Slack Invite Error to Ops channel

### LINKED ISSUE #217: Slack Invite Error should go to Ops channel instead of moderator channel
When an error inviting a user to slack is encountered, it's really up to the staff to handle that rather than the moderators. The error is currently defined here
https://github.com/OperationCode/operationcode-pybot/blob/962238da44d8bb4f719dfddd6521c1fc35791cf0/pybot/endpoints/api/utils.py#L79

Instead, it should go to the Ops channel, which is currently named #oc-ops. I don't think this currently has any bot messages go to it, so it will need to be added here
https://github.com/OperationCode/operationcode-pybot/blob/17647627b5922a0b4ceafbb8ef6a26a16f84cfaf/pybot/endpoints/slack/utils/__init__.py#L9

The default should be `oc-ops` because that's its current name. We'll set the actually channel ID in the production environment variables.

### PR DESCRIPTION
**Pull request by wskinner74**
Changed the pybot to send Slack invite errors to the Ops channel instead of the mod channel.

Fixes #217 

If I understood the original ticket correctly, I changed the "channel" in response to "TICKET_CHANNEL" from "MODERATOR_CHANNEL" in the utils.py file, and "oc-tech" to "oc-ops" in the __init__ file. Let me know if there's anything else that I should have done!

Thanks :)

### CODE REVIEW

**Comment by aaron-suarez** [comment]
Close. We need to call it `OPS_CHANNEL`.

**Comment by wskinner74** [comment]
@aaron-suarez Gotcha, I'll fix that real quick. Does that mean that the __init__ file should include the `TICKET_CHANNEL` line with the `OPS_CHANNEL` line? In that case, would both of them point to `oc-ops`, or would tickets still point to `oc-tech`?

**Comment by aaron-suarez** [comment]
#219 removes the need for TICKET_CHANNEL so you can rename it and point it to oc-ops. We don't need TICKET_CHANNEL anymore

**Comment by wskinner74** [comment]
Sounds good, changes made!

**Comment by wskinner74** [comment]
Looks like it's failing when I take out `TICKET_CHANNEL` due to imports. I think it's just the help_ticket.py file. Should I go ahead and remove that import line?

**Comment by aaron-suarez** [comment]
I'm also not sure what the deal with the old commit is. Do you want to squash all of these commits and rebase onto staging so that all of this is just your commit without that README change?

**Comment by wskinner74** [comment]
Yeah, I can do that.

**Comment by wskinner74** [comment]
@aaron-suarez , okay, I definitely messed something up here when trying to rebase. Should I just start the whole PR over or is there a way to undo?

**Review by aaron-suarez — APPROVED** [review]
LGTM

**Pull request merged**
