### PR TITLE
Require comments and add "non veteran" option in mentor request form

### LINKED ISSUE #138: Non-veterans seeking mentoring can be confused when doing `/mentor` as it doesn't present an option for them
[From Slack](https://operation-code.slack.com/archives/C04D6M3JT/p1574817899404600)

>  I just tried using the mentor shortcut, and it's requiring me to declare myself as a veteran, active duty, or military spouse member, but I've never served. Not sure what to do there.

Suggested solution: add an option

> I am not a veteran, active duty, or a military spouse. I understand that my mentoring request will be receive a lower priority.

### LINKED ISSUE #164: For `/mentor` command, Additional Details should be required
When a mentor request comes in without additional details, it's very difficult for mentors to know if they are able to help with the request. This field should be required.

### PR DESCRIPTION
**Pull request by chynh**
## Changes
Modified request mentor form to show an option for non-veteran and require comments field.
Validation logic and message changed.

Fixes #164 
Fixes #138

### CODE REVIEW

**Comment by chynh** [comment]
Hi,can I get someone to review this PR? It's been open for quite some time.

**Comment by aaron-suarez** [comment]
Hey @chynh, thanks for taking this on. Apologies on the delay. Can we please also add the requestor's affiliation to the message that posts in the mentors-internal channel, so the mentors can see what affiliation they have when they choose whether to claim the request?

https://github.com/OperationCode/operationcode-pybot/blob/962238da44d8bb4f719dfddd6521c1fc35791cf0/pybot/endpoints/airtable/message_templates/messages.py#L4-L15

Something like
```python
         f"User <@{user_id}> has requested a mentor for {service}\n\n" 
         f"Requested Skillset(s): {skillsets.replace(',', ', ')}\n\n"
         f"Requestor Affiliation: {affiliation}"
```

**Comment by chynh** [comment]
Hey @aaron-suarez, I don't have access to Airtable so I couldn't validate whether this works. Let me know if it works or not.

**Review by aaron-suarez — APPROVED** [review]
Looks like it'll work. We'll try in staging and see. Thanks!!

**Pull request merged**
